version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - embedding_network

volumes:
  redis_data:

networks:
  embedding_network:
    driver: bridge
